<div class="recaptcha">
	<input type="checkbox" id="required-recaptcha" name="required-recaptcha" value="" class="hide required-entry validation-failed" style="visibility:hidden; position:absolute; left:-1000000px">
	<div id="g-recaptcha"></div>
</div>
<script type="text/javascript">
	var onloadCallback = function() {
		grecaptcha.render('g-recaptcha', {
			'sitekey': "6LflGW0UAAAAAMPUQMBarSnvTKSVUcyg-9lRz_oR",
			'theme': "light",
			'type': "image",
			'size': "normal",
			'callback': function(response) {
				if (response.length > 0) {
					$('required-recaptcha').writeAttribute('value', 'checked');
					$('required-recaptcha').checked = true;
				}
			}
		});
	};
</script>