
<!-- /** @var \Magento\Catalog\Block\Product\Gallery $block */ -->

<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$mediaUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$categoryIdRoot = 2;
$categoryCollection = $objectManager->create('Magento\Catalog\Model\Category')->getCollection()->addAttributeToSelect('*');
$categoryCollection->addAttributeToFilter('parent_id', $categoryIdRoot);
$categoryCollection->addAttributeToFilter('is_active', 1);
// $categoryCollection->addAttributeToFilter('include_in_menu', 1);
$categoryCollection->setOrder('position', 'ASC');
?>

<!-- collection categories on desktop -->
<div class="list-categories">
	<ul class="list-category-parent">
		<?php if (count($categoryCollection)): ?>
			<?php foreach ($categoryCollection as $category): ?>
				<?php $subcats = $category->getChildrenCategories(); ?>
				<?php $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId()); ?>
				<?php if (count($subcats)): ?>
					<li class="level-0">
						<a href="<?php echo $category->getUrl(); ?>">
							<?php if ($_category->getThumbnail()): ?>
								<img src="<?php echo  $mediaUrl.'catalog/category/'.$_category->getThumbnail(); ?>" alt="<?php echo $category->getName(); ?>">
							<?php else: ?>
								<img src="<?php echo $mediaUrl; ?>wysiwyg/small_image.jpg" alt="<?php echo $category->getName(); ?>">
							<?php endif; ?>
							<span class="name-category-0"><?php echo $category->getName(); ?></span>
						</a>
						<ul class="list-category-child">
							<li class="subcategory-header"><span><?php echo $category->getName(); ?></span></li>
							<li class="all-products"><a href="<?php echo $category->getUrl(); ?>">
									<span><?php echo __('All Products'); ?></span>
								</a></li>
							<?php foreach ($subcats as $subcat): ?>
								<?php $_subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId()); ?>
								<li class="level-1">
									<a href="<?php echo $subcat->getUrl() ?>" title="<?php echo $subcat->getName(); ?>">
										<?php if ($_subCategory->getThumbnail()): ?>
											<img src="<?php echo  $mediaUrl.'catalog/category/'.$_subCategory->getThumbnail(); ?>" alt="<?php echo $subcat->getName(); ?>">
										<?php else: ?>
											<img src="<?php echo $mediaUrl; ?>wysiwyg/small_image.jpg" alt="<?php echo $subcat->getName(); ?>">
										<?php endif; ?>
										<span class="name-category-1">
											<?php echo $subcat->getName(); ?>
										</span>

									</a>
									<?php //$level = 1; ?>
									<?php //_recurse_subcat($subcat->getId(), $level); ?>
								</li>
							<?php endforeach ?>
						</ul>
					</li>
				<?php endif ?>			
			<?php endforeach ?>
		<?php endif ?>		
	</ul>
</div>
<!-- collection categories on mobile -->
<div class="nav-wrap">
	<div id="nav-container" style="transform: translate3d(0px, 0px, 0px);">
		<ul id="nav">
			<?php if (count($categoryCollection)): ?>
			<?php foreach ($categoryCollection as $category): ?>
				<?php $subcats = $category->getChildrenCategories(); ?>
				<?php $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId()); ?>
				<?php if (count($subcats)): ?>
					<li class="level-0 level-top parent" id="category-<?php echo $category->getId(); ?>">
						<a href="<?php echo $category->getUrl(); ?>" class="level-top">
							<span><?php echo $category->getName(); ?></span>
						</a>
						<?php 
						 $level = 0;
						 $levelUl = -1;
						 $nameParent = $category->getName();  
						 $urlParent =  $category->getUrl();
						 ?>
						<?php _recurse_subcat($category->getId(), $level, $levelUl, $nameParent, $urlParent); ?>
					</li>
				<?php endif ?>
			<?php endforeach ?>
		<?php endif ?>
		</ul>
	</div>
</div>
<?php 
function _recurse_subcat($childId,$level,$levelUl, $nameParent, $urlParent ) {
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$children = $objectManager->create('Magento\Catalog\Model\Category')->load($childId)->getChildrenCategories();;
	if(count($children)) {
		$level = $level + 1;
		$levelUl = $levelUl + 1;
		echo '<ul class="category-list level-'.$levelUl.'">';
		echo '<li class="subcategory-header">';
			echo '<div class="button-wrap"><button class="previous-category" data-target="category-'.$childId.'">Back</button></div>';
			echo '<span>'.$nameParent.'</span>';
		echo '</li>';
		echo '<li>';
			echo '<a href="'.$urlParent.'"><span>All Products</span></a>';
		echo '</li>';
		foreach ($children as $subcat) {
			$classParent = "";
			$subsubcat = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId())->getChildrenCategories();;
			if(count($subsubcat)) {
				$classParent = "parent";
			}
			echo '<li class="level-'.$level.' '.$classParent.'" id="category-'.$subcat->getId().'">';
			echo '<a href="'.$subcat->getUrl().'"><span>'.$subcat->getName().'</span></a>';
			_recurse_subcat($subcat->getId(), $level,$levelUl, $subcat->getName(), $subcat->getUrl());
			echo '</li>';
		}
		echo '</ul>';
	}
}

?>
<style type="text/css">
	@media screen and (max-width: 767px){
		body.cms-home.cms-index-index footer.footer{
			margin-top: 15px !important;
		}
	}
	@media screen and (max-width: 991px){
		.list-categories{
			display: none;
		}
		.nav-wrap {
    		overflow: hidden;
    		margin: 0 -15px;
		}
		#nav-container {
    		overflow: hidden;
    		padding: 0 0 1px;
    		position: relative;
    		width: 9000px;
    		-webkit-transform: translate3d(0, 0, 0);
    		-webkit-transition: -webkit-transform 250ms linear;
    		-o-transition: -o-transform 250ms linear;
    		transition: transform 250ms linear;
		}
		#nav-container li a {
    		color: #111;
    		background: url(pub/static/frontend/Mgs/claue_child/en_US/images/bg_shadow_retina.png);
    		background-color: #fff !important;
    		display: block;
    		background-size: 1px 40px;
		}
		#nav-container ul {
    		font-size: 21px;
   		 	margin: 0;
    		width: 100%;
    		float: left;
		}
		#nav-container ul>li>ul {
			display: none;
		}
		#nav-container li a span {
    		background: url(pub/static/frontend/Mgs/claue_child/en_US/images/arrow.png) no-repeat right;
    		display: block;
    		line-height: 20px;
    		padding: 10px 15px;
    		-webkit-background-origin: content-box;
    		background-origin: content-box;
    		background-size: 7px 12px;
		}
		#nav-container li.subcategory-header {
    		background: url(pub/static/frontend/Mgs/claue_child/en_US/images/bg_gradient.png);
    		background-size: auto 45px;
			height: 40px;
    		padding: 6px 10px;
    		text-align: center;
    		font-weight: bold;
		}
		#nav-container li.subcategory-header {
			background-image: url(pub/static/frontend/Mgs/claue_child/en_US/images/bg_gradient_retina.png);
			background-size: auto 45px;
		}
		#nav-container li.subcategory-header .button-wrap {
    		float: left;
    		position: absolute;
    		font-size: 14px;
		}
		#nav-container li.subcategory-header .button-wrap button {
   			background-size: 47px 27px;
   			background: url(pub/static/frontend/Mgs/claue_child/en_US/images/bg_back_btn.png) no-repeat right top;
    		border: none;
    		height: 27px;
    		width: 47px;
    		color: #fff;
    		display: inline-block;
    		font-size: 11px;
    		font-weight: bold;
    		line-height: 27px;
    		margin: 0;
    		padding: 0 0 0 7px;
    		position: relative;
    		z-index: 3;
    		-webkit-appearance: none;
    		appearance: none;
		}
		#nav-container li.subcategory-header span {
    		color: #414141;
    		line-height: 28px;
		}
		
	}
	@media screen and (min-width: 992px){
		.nav-wrap{
			display: none;
		}
	}
</style>
<script type="text/javascript">
	require([
		'jquery'
		], function ($) {
			$(document).ready(function(){
				if ($(window).width() > 992) {
					$('.list-category-parent li.level-0:first-child').addClass('is_active');
					var heightUlChild = $('.list-category-parent li.is_active ul.list-category-child').height();
					$(".list-category-parent").css({
						"padding-bottom":heightUlChild
					});
					$('.list-category-parent li.level-0').hover(function(){
						$('.list-category-parent li.level-0').removeClass('is_active');
						$(this).addClass('is_active');
						var heightUlChilds = $('.list-category-parent li.level-0:first-child ul.list-category-child').height();
						var heightUlChildHover = $('.list-category-parent li.is_active ul.list-category-child').height();
						if(heightUlChildHover < heightUlChilds)
						{
							$(".list-category-parent").css({
								"padding-bottom":heightUlChildHover
							});
						}
						else
						{
							$(".list-category-parent").css({
								"padding-bottom":heightUlChilds
							});
						}
					});
				}	
			}); 
		});
	</script> 
	<script type="text/javascript">
		require([
			'jquery'
			], function ($) {
				$(document).ready(function(){

					var WidthSite = document.body.offsetWidth;
					var sliderPosition = 0,
					viewportWidth = document.body.offsetWidth,
					last,
					diff;
					$("#nav-container ul").each(function(ul) { 
						$("#nav-container ul").width(WidthSite); 
					});

					$("#nav li.parent>a").click(function(e){
						e.preventDefault();
						$(this).closest('#nav-container').append($(this).parent().find('>ul'));
						var numberTransformContainer = $(this).closest('#nav-container').attr("style");
						var cut_str = numberTransformContainer.split('(');
						var cut_str = cut_str[1].split('p');
						var doiso = Number(cut_str[0]);
						if (doiso == 0) {
							var numberTransformAfter = WidthSite+doiso;
						}
						else{
							var numberTransformAfter = WidthSite-doiso;
						}
						document.getElementById("nav-container").style.transform = 'translate3d(-'+numberTransformAfter+'px,0px,0px)';
					});

					$(".previous-category").click(function(e){
						$(this).closest('ul').addClass('is_active');
						var numberTransformContainer1 = $(this).closest('#nav-container').attr("style");
						var cut_strs = numberTransformContainer1.split('(');
						var cut_strs = cut_strs[1].split('p');
						var doisos = Number(cut_strs[0]);
						var numberTransformAfters = WidthSite+doisos;
						var target = $(this).data('target');
						var parent = $(this).parents().parents().parents('.category-list');
						$('#'+target).append(parent);

						document.getElementById("nav-container").style.transform = 'translate3d('+numberTransformAfters+'px,0px,0px)';		
					});
 
				});
			});
		</script>